name: Palai API - Dev
values:
  - key: baseUrl
    value: 'http://localhost:3000'
  - key: accessToken
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbXM3aGdrOWEwMDAwams0b2MzOXJnM3VwIiwicm9sZSI6IkFETUlOIiwianRpIjoiOWUyNjQ5NGI5M2YzNjQ5MDZkY2EzNWYzMTY1NzJiNjgiLCJpYXQiOjE3ODU2MjU2MjEsImV4cCI6MTc4NTYyNjUyMX0.qA6u6GG8a3jnCX-p--G9vuStamCbFoTYLUb-2bxLsvI
  - key: refreshToken
    value: aCe_bKi_mo9FBtbdeuFynKeR2yEJwSQcqZjZVKb3ubm6QKfmgICU_hp0_pdqgagc
  - key: adminEmail
    value: admin@palai.local
  - key: adminPassword
    value: ChangeMeAdmin123!
  - key: userEmail
    value: user@example.com
  - key: userPassword
    value: password123
  - key: palIdOrSlug
    value: lamball
  - key: palId
    value: lamball
  - key: skillIdOrSlug
    value: ''
  - key: passiveIdOrSlug
    value: ''
  - key: itemIdOrSlug
    value: Flecha
  - key: recipeIdOrSlug
    value: ''
  - key: technologyIdOrSlug
    value: ''
  - key: locationIdOrSlug
    value: ''
  - key: bossIdOrSlug
    value: ''
  - key: dungeonIdOrSlug
    value: ''
  - key: workIdOrSlug
    value: ''
  - key: jobId
    value: cms7koakf0004jk68p0bc3m9g
color: 120
