name: Palai API - Dev
values:
  - key: baseUrl
    value: 'http://localhost:3000'
  - key: accessToken
    value: ''
  - key: refreshToken
    value: ''
  - key: adminEmail
    value: admin@palai.local
  - key: adminPassword
    value: ChangeMeAdmin123!
  - key: userEmail
    value: user@example.com
  - key: userPassword
    value: password123
  - key: palIdOrSlug
    value: lamball
  - key: palId
    value: lamball
  - key: skillIdOrSlug
    value: ''
  - key: passiveIdOrSlug
    value: ''
  - key: itemIdOrSlug
    value: ''
  - key: recipeIdOrSlug
    value: ''
  - key: technologyIdOrSlug
    value: ''
  - key: locationIdOrSlug
    value: ''
  - key: bossIdOrSlug
    value: ''
  - key: dungeonIdOrSlug
    value: ''
  - key: workIdOrSlug
    value: ''
  - key: jobId
    value: ''
color: 120
