name: Palai API - Prod
values:
  - key: baseUrl
    value: 'https://api.palai.app'
  - key: accessToken
    value: ''
  - key: refreshToken
    value: ''
  - key: adminEmail
    value: ''
  - key: adminPassword
    value: ''
  - key: userEmail
    value: ''
  - key: userPassword
    value: ''
  - key: palIdOrSlug
    value: lamball
  - key: palId
    value: lamball
  - key: skillIdOrSlug
    value: ''
  - key: passiveIdOrSlug
    value: ''
  - key: itemIdOrSlug
    value: ''
  - key: recipeIdOrSlug
    value: ''
  - key: technologyIdOrSlug
    value: ''
  - key: locationIdOrSlug
    value: ''
  - key: bossIdOrSlug
    value: ''
  - key: dungeonIdOrSlug
    value: ''
  - key: workIdOrSlug
    value: ''
  - key: jobId
    value: ''
color: 0
